#!/bin/sh
echo "Content-type: text/html"
echo

cat <<t
<html lang="pt-br">
    <head>
        <meta http-equiv="refresh" content="10">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
<body>
    <div>
        <h2>Listando Namespaces</h2>
        <pre>$(kubectl get namespaces -o custom-columns="Name:.metadata.name")</pre>
    </div>

</body>
</html>
t